// rasterize.ts — Server-only SVG→PNG rasterizer via @resvg/resvg-js (NAPI-RS / pure Rust).
//
// NO "use client" — this file is server-only. Import only from route handlers or server modules.
// @resvg/resvg-js ships platform-specific NAPI .node binaries (e.g. @resvg/resvg-js-darwin-arm64
// locally, @resvg/resvg-js-linux-x64-gnu on Vercel Lambda). It must be listed in
// next.config.ts serverExternalPackages so Next.js/Turbopack does not attempt to bundle the
// .node binary at build time (RESEARCH.md Pitfall 2 — without this entry, the route throws
// "Cannot find module '@resvg/resvg-js'" at runtime on Vercel).
//
// Security (T-7-04): the SVG fed to this function must be generated by renderChartSvgString()
// from buildChartData(group) — values from vm.hospMetrics (validated z.number().nullable() by
// HospMetricSchema), colors from the closed CHART_SERIES enum. No untrusted/remote SVG, no
// user-controlled string → no SVG/XXE/SSRF injection surface.

import { Resvg } from "@resvg/resvg-js";
import { getChartFontFiles, CHART_FONT_FAMILY } from "@/lib/charts/chart-font";

/**
 * Rasterizes an SVG string to a PNG Buffer using @resvg/resvg-js.
 *
 * Used in buildReportDocxBuffer to create ImageRun chart PNGs for OOXML embedding.
 * Keep width/height small (≤300×140) to respect the DOCX-01 size budget — 4 chart PNGs
 * at 300×140 add ~60–200 KB total, well within the 4.5 MB limit (RESEARCH.md Pitfall 3).
 *
 * WR-03: width-only by design. resvg's `fitTo: { mode: "width" }` preserves the SVG's
 * intrinsic aspect ratio, so output height is governed by the width/height attributes the
 * caller bakes into the SVG via renderChartSvgString(data, w, h) — NOT by a height arg here.
 * The previous dead `height` param hid this coupling; removed to make the contract explicit.
 *
 * @param svgString — A valid SVG markup string (from renderChartSvgString).
 * @param width — Output PNG width in pixels (default 300); height follows the SVG's aspect ratio.
 * @returns Buffer whose first 8 bytes are the PNG magic: 0x89 0x50 0x4E 0x47 0x0D 0x0A 0x1A 0x0A.
 */
export function svgToPngBuffer(svgString: string, width = 300): Buffer {
  // RESVG-FONT-01: supply an embedded font + disable system fonts so SVG <text> renders
  // identically on macOS and Vercel Lambda (Lambda has no system fonts → blank chart labels).
  const resvg = new Resvg(svgString, {
    fitTo: { mode: "width", value: width },
    font: {
      loadSystemFonts: false,
      fontFiles: getChartFontFiles(),
      defaultFontFamily: CHART_FONT_FAMILY,
      sansSerifFamily: CHART_FONT_FAMILY,
    },
  });
  const pngData = resvg.render();
  return Buffer.from(pngData.asPng());
}
